### PR TITLE
Added altert which pops up if video player is unable to play the provided file

### PR DESCRIPTION
**Pull request by murezzda**
**Is your Pull Request request related to another [issue](https://github.com/bbc/react-transcript-editor/issues) in this repository ?**      
Related to #178.

**Describe what the PR does**    
After hitting the play button, the player checks if the video player is playing the video. If this is not the case, an `alert` is triggered informing the user that the provided file is not compatible with the html5 video player.

**State whether the PR is ready for review or whether it needs extra work**    
The given PR would be sufficient for us for the moment. Possible improvements are described in the issue page, but I can't say if I'm able to work on these in the near future.

### CODE REVIEW

**Comment by murezzda** [comment]
Hi @jamesdools, we have some problems with wav's containing audio with is mpeg1/2 encoded. I could provide you a sample file if you need it. 

I'm not sure what you mean by "load not play", how could I spot the difference?

Regarding the `canPlayType`, that would be probably the prefered solution but I'm not sure if this only checks the container or also the coded information.

**Comment by pietrop** [comment]
This might be interesting via @bevand10 [HTML5 Audio — The State of Play
Tuesday, May 8th, 2012](http://html5doctor.com/html5-audio-the-state-of-play)  by @maboa

**Comment by pietrop** [comment]
Another option mentioned by @bevand10  is to use the `accept` attribute in the `input` element when the users upload the file, see [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file)

Also [MDN - Media formats for HTML audio and video](https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats) for a comprehensive list of HTML5 supported media.

**Comment by pietrop** [comment]
Example of mime types check via @bevand10  [goldfire/howler.js/src/howler.core.js#L256](https://github.com/goldfire/howler.js/blob/master/src/howler.core.js#L256)

**Pull request closed without merging**
